"""
models.py

This module defines structured data models using Pydantic for use within the developer tools research agent.
These models are used to validate, serialize, and track information throughout the research workflow.

Key Classes:
- CompanyAnalysis: Structured analysis of a developer-facing tool or platform
- CompanyInfo: General metadata and developer-specific details about a company/tool
- ResearchState: Captures the state of a multi-step research session
"""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel


class CompanyAnalysis(BaseModel):
    """
    Represents a structured analysis of a developer tool or company based on its website content.

    This model is designed to be populated by an LLM (language model) or human analyst,
    focusing on features relevant to software developers.
    """

    pricing_model: str  # One of: "Free", "Freemium", "Paid", "Enterprise", "Unknown"
    is_open_source: Optional[bool] = None  # True/False if known, None if unclear
    tech_stack: List[str] = []  # Programming languages, frameworks, APIs, etc.
    description: str = ""  # Short summary of the tool's purpose
    api_available: Optional[bool] = None  # Whether APIs or SDKs are explicitly mentioned
    language_support: List[str] = []  # Languages supported (e.g., Python, JavaScript)
    integration_capabilities: List[str] = []  # Tools/platforms it integrates with


class CompanyInfo(BaseModel):
    """
    Stores metadata and technical information about a specific company or tool.

    Includes general website data and developer-focused fields such as API support,
    programming language compatibility, and integrations.
    """

    name: str  # Name of the company or tool
    description: str  # General or LLM-generated description of the tool
    website: str  # URL to the official site or documentation
    pricing_model: Optional[str] = None  # Optionally extracted pricing info
    is_open_source: Optional[bool] = None  # Open source status (if known)
    tech_stack: List[str] = []  # Technologies used or supported
    competitors: List[str] = []  # Optional field for listing related tools

    # Developer-specific fields
    api_available: Optional[bool] = None  # Whether the tool offers an API or SDK
    language_support: List[str] = []  # Supported programming languages
    integration_capabilities: List[str] = []  # Other tools it can integrate with
    developer_experience_rating: Optional[str] = None  # e.g., "Poor", "Good", "Excellent"


class ResearchState(BaseModel):
    """
    Tracks the state of a research workflow session.

    This model is passed between steps in a LangGraph state machine,
    accumulating data as the research pipeline progresses.
    """

    query: str  # The original user input or search term
    extracted_tools: List[str] = []  # Tool names extracted from articles/content
    companies: List[CompanyInfo] = []  # Analyzed companies/tools with structured info
    search_results: List[Dict[str, Any]] = []  # Raw search metadata (optional)
    analysis: Optional[str] = None  # Final recommendation/comment generated by the LLM